"""Add report_logo to app_setting

Revision ID: 0ed3ee734b2c
Revises: 155121fb044d
Create Date: 2026-09-17 17:29:17.069101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed3ee734b2c'
down_revision = '155121fb044d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_logo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.drop_column('report_logo')

    # ### end Alembic commands ###
