"""add app_setting table

Revision ID: 155121fb044d
Revises: ba2d18c30b52
Create Date: 2026-09-10 15:59:54.188731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155121fb044d'
down_revision = 'ba2d18c30b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('login_logo', sa.String(length=255), nullable=True),
    sa.Column('sidebar_logo', sa.String(length=255), nullable=True),
    sa.Column('favicon', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_setting')
    # ### end Alembic commands ###
