"""Add GAD Automation Globe valve lookup tables

Revision ID: fbc0e1ec8c49
Revises: fb8adab752c2
Create Date: 2026-09-10 10:35:39.435365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc0e1ec8c49'
down_revision = 'fb8adab752c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ga_crosssec_globe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_style', sa.String(length=50), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('bonnet_type', sa.String(length=50), nullable=False),
    sa.Column('trim_type', sa.String(length=50), nullable=False),
    sa.Column('balancing', sa.String(length=50), nullable=False),
    sa.Column('bal_seal_type', sa.String(length=50), nullable=False),
    sa.Column('seat_type', sa.String(length=50), nullable=False),
    sa.Column('packing_type', sa.String(length=50), nullable=False),
    sa.Column('flow_direction', sa.String(length=50), nullable=False),
    sa.Column('drawing_no', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ga_dim_act_globe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actuator_type', sa.String(length=50), nullable=False),
    sa.Column('actuator_size', sa.String(length=50), nullable=False),
    sa.Column('hand_wheel', sa.String(length=20), nullable=False),
    sa.Column('travel_stop', sa.String(length=50), nullable=False),
    sa.Column('d', sa.String(length=50), nullable=True),
    sa.Column('e', sa.String(length=50), nullable=True),
    sa.Column('f', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ga_dim_valve_globe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body_style', sa.String(length=50), nullable=False),
    sa.Column('end_connection', sa.String(length=50), nullable=False),
    sa.Column('bonnet_type', sa.String(length=50), nullable=False),
    sa.Column('end_finish', sa.String(length=50), nullable=False),
    sa.Column('series', sa.String(length=10), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.String(length=50), nullable=False),
    sa.Column('stem_dia', sa.String(length=50), nullable=False),
    sa.Column('a', sa.String(length=50), nullable=True),
    sa.Column('b', sa.String(length=50), nullable=True),
    sa.Column('c', sa.String(length=50), nullable=True),
    sa.Column('ar', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ga_globe_hookup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actuator', sa.String(length=50), nullable=False),
    sa.Column('spring', sa.String(length=50), nullable=False),
    sa.Column('air_fail_action', sa.String(length=50), nullable=False),
    sa.Column('positioner', sa.String(length=50), nullable=False),
    sa.Column('hand_auto', sa.String(length=50), nullable=False),
    sa.Column('limit_switch', sa.String(length=50), nullable=False),
    sa.Column('position_trans', sa.String(length=50), nullable=False),
    sa.Column('volume_booster', sa.String(length=50), nullable=False),
    sa.Column('spool_valve', sa.String(length=50), nullable=False),
    sa.Column('lock_valve', sa.String(length=50), nullable=False),
    sa.Column('solenoid_valve', sa.String(length=50), nullable=False),
    sa.Column('schematic_no', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ga_globe_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valve_series', sa.String(length=10), nullable=False),
    sa.Column('body_style', sa.String(length=50), nullable=False),
    sa.Column('valve_size', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.String(length=100), nullable=False),
    sa.Column('end_connection', sa.String(length=50), nullable=False),
    sa.Column('bonnet_type', sa.String(length=50), nullable=False),
    sa.Column('flow_direction', sa.String(length=50), nullable=False),
    sa.Column('actuator_series', sa.String(length=50), nullable=False),
    sa.Column('actuator_type', sa.String(length=200), nullable=False),
    sa.Column('actuator_size', sa.String(length=100), nullable=False),
    sa.Column('traval_stop', sa.String(length=100), nullable=False),
    sa.Column('hw', sa.String(length=20), nullable=False),
    sa.Column('drawing_no', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ga_globe_table')
    op.drop_table('ga_globe_hookup')
    op.drop_table('ga_dim_valve_globe')
    op.drop_table('ga_dim_act_globe')
    op.drop_table('ga_crosssec_globe')
    # ### end Alembic commands ###
